aluno = input('Digite o nome do aluno: ')
nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))
nota3 = float(input('Digite a terceira nota: '))
media = (nota1 + nota2 + nota3) / 3
print(f'{aluno}')
print(f'Nota 1: {nota1}')
print(f'Nota 2: {nota2}')
print(f'Nota 3: {nota3}')
print()
print('='*5 + 'Boletim'.upper() + '='*5)
print()
print(f'Média final: {media:.2f}')