n1 = int(input('Escolha qualquer número: '))
n2 = int(input('Mais um vai: '))
n3 = int(input('Mais um: '))
n4 = int(input('Mais um: '))
n5 = int(input('Mais um: '))
n6 = int(input('Mais um: '))
n7 = int(input('Mais um: '))
n8 = int(input('Mais um: '))
n9 = int(input('Mais um: '))
n10 = int(input('Mais um: '))
n11 = int(input('Mais um: '))
n12 = int(input('Mais um: '))
n13 = int(input('Mais um: '))
s = n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10 +n11 + n12 + n13
print('A valor de {} + {} + {} + {} + {} + {} + {} + {} + {} + {} + {} + {} + {} é igual {}'.format(n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13, s))